# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: vs2017-win2016
  demands: Cmd

trigger:
  branches:
    include:
      - dev
      - master

pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true
  branches:
    include: [ dev, master ] # branch names which will trigger a build

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: false  # whether to fetch clean each time
  submodules: recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
  persistCredentials: true
- task: BatchScript@1
  displayName: 'FAKE Build'
  inputs:
    filename: build.cmd
    arguments: 'All'
 - task: CopyFiles@2
    displayName: 'Copy Build Output'
    inputs:
      sourceFolder: bin\nuget
      contents: '**\*'
      targetFolder: $(Build.ArtifactStagingDirectory)
      continueOnError: boolean  # 'true' if future steps should run even if this step fails; defaults to 'false'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Petabridge.Templates-$(Build.BuildId)'